#!/bin/sh

if env | grep -q '^VIRTUAL_ENV='
then
    source deactivate
fi

source env/server/bin/activate

if [[ -n "$OK_TEST_DIR" ]];
    then echo $OK_TEST_DIR; 
    else OK_TEST_DIR='all';
fi

FLASK_CONF=TEST python server/apptest.py --quiet --dir $OK_TEST_DIR $@
RESULT=$?

deactivate
exit $RESULT
