"""Job logs should use mediumtext

Revision ID: 131bc6d9d550
Revises: 5706baf73b01
Create Date: 2016-09-16 16:29:15.707476

"""

# revision identifiers, used by Alembic.
revision = '131bc6d9d550'
down_revision = '5706baf73b01'

from alembic import op
import sqlalchemy as sa
import server
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'log',
               existing_type=mysql.TEXT,
               type_=mysql.MEDIUMTEXT,
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'failed',
               existing_type=mysql.MEDIUMTEXT,
               type_=mysql.TEXT,
               existing_nullable=False)
    ### end Alembic commands ###
