"""empty message

Revision ID: 6504bfe5203c
Revises: e2cfee316e0a
Create Date: 2016-08-25 20:28:04.737541

"""

# revision identifiers, used by Alembic.
revision = '6504bfe5203c'
down_revision = 'e2cfee316e0a'

from alembic import op
import sqlalchemy as sa
import server


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.String(length=40), nullable=False),
    sa.Column('client_secret', sa.String(length=55), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('redirect_uris', server.models.StringList(), nullable=False),
    sa.Column('default_scopes', server.models.StringList(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_client_user_id_user')),
    sa.PrimaryKeyConstraint('client_id', name=op.f('pk_client'))
    )
    op.create_index(op.f('ix_client_client_secret'), 'client', ['client_secret'], unique=True)
    op.create_table('grant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('redirect_uri', sa.String(length=255), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('scopes', server.models.StringList(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], name=op.f('fk_grant_client_id_client')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_grant_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grant'))
    )
    op.create_index(op.f('ix_grant_code'), 'grant', ['code'], unique=False)
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token_type', sa.String(length=40), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('scopes', server.models.StringList(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], name=op.f('fk_token_client_id_client')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_token_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token')),
    sa.UniqueConstraint('access_token', name=op.f('uq_token_access_token')),
    sa.UniqueConstraint('refresh_token', name=op.f('uq_token_refresh_token'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.drop_index(op.f('ix_grant_code'), table_name='grant')
    op.drop_table('grant')
    op.drop_index(op.f('ix_client_client_secret'), table_name='client')
    op.drop_table('client')
    ### end Alembic commands ###
