"""Publish Scores for Assignments

Revision ID: 6ce2cf5c4534
Revises: f7f27412d13f
Create Date: 2016-10-22 16:39:49.635725

"""

# revision identifiers, used by Alembic.
revision = '6ce2cf5c4534'
down_revision = 'f7f27412d13f'

from alembic import op
import sqlalchemy as sa
import server


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('published_scores', server.models.StringList(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'published_scores')
    ### end Alembic commands ###
