"""Add More Indicies To Tables

Revision ID: 7b6a65c708b9
Revises: 7e1d5c529924
Create Date: 2016-10-25 20:58:47.659852

"""

# revision identifiers, used by Alembic.
revision = '7b6a65c708b9'
down_revision = '7e1d5c529924'

from alembic import op
import sqlalchemy as sa
import server


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_backup_flagged'), 'backup', ['flagged'], unique=False)
    op.create_index(op.f('ix_backup_submit'), 'backup', ['submit'], unique=False)
    op.create_index(op.f('ix_backup_created'), 'backup', ['created'], unique=False)
    op.create_index(op.f('ix_enrollment_role'), 'enrollment', ['role'], unique=False)
    op.create_index(op.f('ix_score_archived'), 'score', ['archived'], unique=False)
    op.create_index(op.f('ix_score_kind'), 'score', ['kind'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_kind'), table_name='score')
    op.drop_index(op.f('ix_score_archived'), table_name='score')
    op.drop_index(op.f('ix_enrollment_role'), table_name='enrollment')
    op.drop_index(op.f('ix_backup_submit'), table_name='backup')
    op.drop_index(op.f('ix_backup_flagged'), table_name='backup')
    op.drop_index(op.f('ix_backup_created'), table_name='backup')
    ### end Alembic commands ###
