"""Custom submission times for Backup

Revision ID: 7e1d5c529924
Revises: 6ce2cf5c4534
Create Date: 2016-10-25 20:31:14.423524

"""

# revision identifiers, used by Alembic.
revision = '7e1d5c529924'
down_revision = '6ce2cf5c4534'

from alembic import op
import sqlalchemy as sa
import server
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backup', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('backup', sa.Column('custom_submission_time', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_backup_creator_id_user'), 'backup', 'user', ['creator_id'], ['id'])
    op.drop_column('backup', 'extension')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backup', sa.Column('extension', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_backup_creator_id_user'), 'backup', type_='foreignkey')
    op.drop_column('backup', 'custom_submission_time')
    op.drop_column('backup', 'creator_id')
    ### end Alembic commands ###
