"""Create ExternalFile Table

Revision ID: 925060c32677
Revises: 47e948205fbd
Create Date: 2016-12-31 04:14:44.776368

"""

# revision identifiers, used by Alembic.
revision = '925060c32677'
down_revision = '47e948205fbd'

from alembic import op
import sqlalchemy as sa
import server


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_file',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('object_name', sa.String(length=1024), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], name=op.f('fk_external_file_assignment_id_assignment')),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_external_file_course_id_course')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_external_file_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_file'))
    )
    op.create_index(op.f('ix_external_file_assignment_id'), 'external_file', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_external_file_course_id'), 'external_file', ['course_id'], unique=False)
    op.create_index(op.f('ix_external_file_user_id'), 'external_file', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_file_user_id'), table_name='external_file')
    op.drop_index(op.f('ix_external_file_course_id'), table_name='external_file')
    op.drop_index(op.f('ix_external_file_assignment_id'), table_name='external_file')
    op.drop_table('external_file')
    # ### end Alembic commands ###
