"""empty message

Revision ID: 933a783c7654
Revises: 94d2839daa08
Create Date: 2016-06-17 03:42:29.141777

"""

# revision identifiers, used by Alembic.
revision = '933a783c7654'
down_revision = '94d2839daa08'

from alembic import op
import sqlalchemy as sa
import server



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('website', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'website')
    ### end Alembic commands ###
