"""empty message

Revision ID: 9bc6f244678d
Revises: 1266914000cd
Create Date: 2019-01-23 21:16:14.715499

"""

# revision identifiers, used by Alembic.
revision = '9bc6f244678d'
down_revision = '1266914000cd'

from alembic import op
import sqlalchemy as sa
import server


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('autograder_url', sa.String(length=255), server_default='https://autograder.cs61a.org', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'autograder_url')
    # ### end Alembic commands ###
