"""Create Extensions

Revision ID: c71e52b908e6
Revises: 925060c32677
Create Date: 2017-02-24 13:07:04.333961

"""

# revision identifiers, used by Alembic.
revision = 'c71e52b908e6'
down_revision = 'f861ec2fe9ff'

from alembic import op
import sqlalchemy as sa
import server
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('custom_submission_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], name=op.f('fk_extension_assignment_id_assignment')),
    sa.ForeignKeyConstraint(['staff_id'], ['user.id'], name=op.f('fk_extension_staff_id_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_extension_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extension')),
    sa.UniqueConstraint('assignment_id', 'user_id', name=op.f('uq_extension_assignment_id_user_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extension')
    # ### end Alembic commands ###
