"""empty message

Revision ID: ca9a10db0a21
Revises: 94d2839daa08
Create Date: 2016-06-17 03:45:59.885699

"""

# revision identifiers, used by Alembic.
revision = 'ca9a10db0a21'
down_revision = '94d2839daa08'

from alembic import op
import sqlalchemy as sa
import server
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('website', sa.String(length=255), nullable=True))
    op.drop_constraint('fk_course_creator_id_user', 'course', type_='foreignkey')
    op.drop_column('course', 'creator_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('creator_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_course_creator_id_user', 'course', 'user', ['creator_id'], ['id'])
    op.drop_column('course', 'website')
    ### end Alembic commands ###
