"""Improved Moss Integration

Revision ID: d9ef8b054eb4
Revises: c71e52b908e6
Create Date: 2017-05-16 23:24:55.283627

"""

# revision identifiers, used by Alembic.
revision = 'd9ef8b054eb4'
down_revision = 'c71e52b908e6'

from alembic import op
import sqlalchemy as sa
import server


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moss_result',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submissionA_id', sa.Integer(), nullable=False),
    sa.Column('submissionB_id', sa.Integer(), nullable=False),
    sa.Column('similarityA', sa.Integer(), nullable=False),
    sa.Column('similarityB', sa.Integer(), nullable=False),
    sa.Column('matchesA', server.models.JsonBlob(), nullable=False),
    sa.Column('matchesB', server.models.JsonBlob(), nullable=False),
    sa.Column('tags', server.models.StringList(), nullable=False),
    sa.ForeignKeyConstraint(['submissionA_id'], ['backup.id'], name=op.f('fk_moss_result_submissionA_id_backup')),
    sa.ForeignKeyConstraint(['submissionB_id'], ['backup.id'], name=op.f('fk_moss_result_submissionB_id_backup')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moss_result'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moss_result')
    # ### end Alembic commands ###
