"""add extension requests

Revision ID: f814f6fadedf
Revises: fb49c4643d00
Create Date: 2021-06-20 23:42:39.930073

"""

# revision identifiers, used by Alembic.
revision = 'f814f6fadedf'
down_revision = 'fb49c4643d00'

from alembic import op
import sqlalchemy as sa
import server
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_request',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', mysql.MEDIUMTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], name=op.f('fk_extension_request_assignment_id_assignment')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_extension_request_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extension_request')),
    sa.UniqueConstraint('assignment_id', 'user_id', name=op.f('uq_extension_request_assignment_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extension_request')
    # ### end Alembic commands ###
