import os

ENV = 'test'
SECRET_KEY = os.getenv('OK_SESSION_KEY', 'testkey')
CACHE_TYPE = 'simple'

DEBUG = True
ASSETS_DEBUG = True
TESTING_LOGIN = True
DEBUG_TB_INTERCEPT_REDIRECTS = False

SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_DATABASE_URI = 'sqlite:///../oktest.db'
WTF_CSRF_CHECK_DEFAULT = False
WTF_CSRF_ENABLED = False

CACHE_TYPE = 'simple'

GOOGLE_CONSUMER_KEY = ''
