# ok settings

dockerTag: latest
dockerRegistry: changeme
okEnv: prod
logLevel: INFO

# tls settings

letsencryptDomain: changeme

nginx-ingress:
  rbac:
    create: false
    createRole: false
    createClusterRole: false
  controller:
    replicaCount: 3

kube-lego:
  config:
    LEGO_EMAIL: changeme
    LEGO_URL: https://acme-v01.api.letsencrypt.org/directory
